routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/ciao/{name?}/{surname?}/{year?}', 'HelloController@index')->name('hello')
    ->where('name', '[a-z,A-Z]+')
    ->where('surname', '[a-z]+')
    ->where('year', '[0-9]+');

//Route::resource('table', 'TableController')->only('index');

Route::get('table/{n?}', 'TableController@index')->where('n', '[0-9]+');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function (){
    Route::resource('actors', 'ActorController');
    Route::resource('movies', 'MovieController')->only('show', 'edit', 'update', 'destroy');
    Route::resource('permissions', 'PermissionController');
    Route::resource('users', 'UserController');
    Route::resource('todos', 'TodoController');
    Route::resource('users.permission', 'PermissionUserController');
    Route::get('/homejs', function (){
        return view('homejs');
    });
});





//Route::get('actors', 'ActorController@index');
//Route::post('actors', 'ActorController@store');
//Route::get('actors/{id}', 'ActorController@show');
//Route::put('actors/{id}', 'ActorController@update');
//Route::delete('actors/{id}', 'ActorController@destroy');
//
//Route::get('actors/create', 'ActorController@create');
//Route::get('actors/{id}/edit', 'ActorController@edit');

resources/views/movies/edit.blade.php
@extends('layouts.app')
@section('title', 'Modifica '.$movie->title)
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Modifica {{$movie->title}}</div>

                    <div class="card-body">
                        <form action="{{route('movies.update', $movie->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label >Titolo</label>
                                <input type="text" name="title" class="form-control" value="{{$movie->title}}" placeholder="Titolo film">
                            </div>
                            <div class="form-group">
                                <label >Anno</label>
                                <input type="text" name="year" class="form-control" value="{{$movie->year}}" placeholder="Anno film">
                            </div>
                            <div class="form-group">
                                <label >Descrizione</label>
                                <textarea class="form-control" name="description" placeholder="Descrizione film">{{$movie->description}}</textarea>
                            </div>
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach($errors->all() as $error)
                                            <li>{{$error}}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="d-flex justify-content-around">
                                <a href="{{route('movies.show', $movie->id)}}" class="btn btn-primary"> Annulla</a>
                                <button type="submit" class="btn btn-primary float-right">Modifica</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/movies/show.blade.php
@extends('layouts.app')
@section('title', $movie->title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        {{$movie->title}}
                        <a href="{{route('movies.edit', $movie->id)}}" class="float-right">
                            <i class="fa fa-edit" aria-hidden="true"></i>
                        </a>

                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">

                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-12">
                                        Titolo: {{$movie->title}}
                                    </div>
                                    <div class="col-12">
                                        Anno: {{$movie->year}}
                                    </div>
                                    <div class="col-12">
                                        Descrizione: {{$movie->description}}
                                    </div>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <a href="{{route('actors.show', $movie->actor_id)}}" class="btn btn-primary">Lista Film</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection