routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/ciao/{name?}/{surname?}/{year?}', 'HelloController@index')->name('hello')
    ->where('name', '[a-z,A-Z]+')
    ->where('surname', '[a-z]+')
    ->where('year', '[0-9]+');

//Route::resource('table', 'TableController')->only('index');

Route::get('table/{n?}', 'TableController@index')->where('n', '[0-9]+');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function (){
    Route::resource('actors', 'ActorController');
    Route::resource('movies', 'MovieController')->only('show', 'edit', 'update', 'destroy');
    Route::resource('permissions', 'PermissionController');
    Route::resource('users', 'UserController');
    Route::resource('todos', 'TodoController');
    Route::resource('users.permission', 'PermissionUserController');
    Route::get('/homejs', function (){
        return view('homejs');
    });
});





//Route::get('actors', 'ActorController@index');
//Route::post('actors', 'ActorController@store');
//Route::get('actors/{id}', 'ActorController@show');
//Route::put('actors/{id}', 'ActorController@update');
//Route::delete('actors/{id}', 'ActorController@destroy');
//
//Route::get('actors/create', 'ActorController@create');
//Route::get('actors/{id}/edit', 'ActorController@edit');

app/Actor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{
    protected $fillable = [
        'name', 'surname', 'year', 'photo'
    ];

    public function movies(){
        return $this->hasMany('App\Movie');
    }

    public function getPathAttribute(){
        $url = $this->photo;
        if(!stristr($url, 'http')){
            $url = '/storage/'.$url;
        }
        return $url;
    }
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;

use App\Actor;
use App\Http\Requests\ActorRequest;
use App\Http\Traits\TestTrait;
use App\Http\Traits\WrapperCache;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class ActorController extends Controller
{
    use WrapperCache;

    public $nameCache;

    public function __construct()
    {
        $this->nameCache = 'actors';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $name = 'Lino';
        //dd(DB::select("SELECT * FROM actors WHERE name = ?", [$name]));
        //dd(DB::table('actors')->get());
        //dd(DB::table('actors')->select('name', 'surname')->get());
        //dd(DB::table('actors')->join('movies', 'actors.id', '=', 'movies.actor_id')->get());
        //dd(Actor::all('name', 'surname'));
//        if(Cache::has('actors')){
//            $cacheSave = Cache::get('actors');
//            dd($cacheSave);
//        }

        $actors = Cache::rememberForever($this->nameCache, function (){
            return Actor::all();
        });
//        Cache::store()->put('actors', $actors, 10);
        return view('actors.index', compact('actors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('actors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ActorRequest $request)
    {
//        $this->validate($request, [
//            'name' => 'required|alpha',
//            'surname' => 'required',
//            'year' => 'required'
//        ], [
//            'name.required' => 'Il campo nome è obbligatorio',
//            'name.alpha' => 'Il campo nome non può essere numerico',
//            'surname.required' => 'Il cognome è obbligatorio',
//            'year.required' => "Non puoi nascondere l'età"
//        ]);
        $actor = Actor::create($request->all());
        $this->removeList();
        return redirect()->route('actors.show', $actor->id);
    }


    public function show($id)
    {
        $actor = Cache::rememberForever($this->nameCache.'-'.$id,  function () use($id){
           return Actor::findOrFail($id)->load('movies');
        });
       // $actor = Actor::findOrFail($id);
       // dd($actor->movies);

        return view('actors.show', compact('actor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Actor  $actor
     * @return \Illuminate\Http\Response
     */
    public function edit(Actor $actor)
    {
        return view('actors.edit', compact('actor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ActorRequest  $request
     * @param  \App\Actor  $actor
     * @return \Illuminate\Http\Response
     */
    public function update(ActorRequest $request, Actor $actor)
    {
//        $this->validate($request, [
//            'name' => 'required|alpha',
//            'surname' => 'required',
//            'year' => 'required'
//        ], [
//            'name.required' => 'Il campo nome è obbligatorio',
//            'name.alpha' => 'Il campo nome non può essere numerico',
//            'surname.required' => 'Il cognome è obbligatorio',
//            'year.required' => "Non puoi nascondere l'età"
//        ]);

        $data = $request->all();
        if ($request->hasFile('imageFile')) {
           $file = $request->file('imageFile');
           $fileName = $file->store('images');
           $data['photo'] = $fileName;
        }
        $actor->update($data);
        $this->removeList();
        $this->removeSingle($actor->id);
        return redirect()->route('actors.show', $actor->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Actor  $actor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Actor $actor)
    {
        //$actor->movies()->delete();
        $actor->delete();
        return redirect()->route('actors.index');
    }
}

resources/views/actors/create.blade.php
@extends('layouts.app')
@section('title', 'Crea nuovo attore')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Crea attore</div>

                    <div class="card-body">
                        <form action="{{route('actors.store')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label >Nome</label>
                                <input type="text" name="name" class="form-control" value="{{old('name')}}" placeholder="Nome attore">
                            </div>
                            <div class="form-group">
                                <label >Cognome</label>
                                <input type="text" name="surname" class="form-control" value="{{old('surname')}}" placeholder="Cognome attore">
                            </div>
                            <div class="form-group">
                                <label >Anno di nascita</label>
                                <input type="number" name="year" class="form-control" value="{{old('year')}}" placeholder="Data di nascita">
                            </div>
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach($errors->all() as $error)
                                            <li>{{$error}}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <button type="submit" class="btn btn-primary float-right">Salva</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/actors/edit.blade.php
@extends('layouts.app')
@section('title', 'Modifica '.$actor->name.' '.$actor->surname)
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Modifica {{$actor->name}} {{$actor->surname}}</div>

                    <div class="card-body">
                        <form action="{{route('actors.update', $actor->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label >Nome</label>
                                <input type="text" name="name" class="form-control" value="{{$actor->name}}" placeholder="Nome attore">
                            </div>
                            <div class="form-group">
                                <label >Cognome</label>
                                <input type="text" name="surname" class="form-control" value="{{$actor->surname}}" placeholder="Cognome attore">
                            </div>
                            <div class="form-group">
                                <label >Anno di nascita</label>
                                <input type="number" name="year" class="form-control" value="{{$actor->year}}" placeholder="Data di nascita">
                            </div>
                            <div class="form-group">
                                <input type="file" name="imageFile">
                            </div>
                            @if($actor->photo)
                                <div class="p-2">
                                    <img width="300" src="{{$actor->path}}" alt="{{$actor->name}} {{$actor->surname}}">
                                </div>
                            @endif
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach($errors->all() as $error)
                                            <li>{{$error}}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <button type="submit" class="btn btn-primary float-right">Modifica</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/actors/index.blade.php
@extends('layouts.app')
@section('title', 'Lista attori')

@section('content')
    <div class="container">
        <div class="row actor justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Lista attori</div>

                    <div class="card-body">
                        @foreach($actors as $actor)
                            <div class="row my-3 badge-primary">
                                <div class="col-3">
                                    @if($actor->photo)
                                     <img src="{{$actor->path}}" alt="{{$actor->name}} {{$actor->surname}}" class="img-thumbnail m-1">
                                    @endif
                                </div>
                                <div class="col-9">
                                    <div class="row">
                                        <div class="col-8">
                                            <h4>{{$actor->name}} {{$actor->surname}}</h4>
                                        </div>
                                        <div class="col-2">
                                            <a href="{{route('actors.show', $actor->id)}}">
                                                <i class="fa fa-address-card"></i>
                                            </a>
                                        </div>
                                        <div class="col-2">
                                            <form action="{{route('actors.destroy', $actor->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-primary-outline">
                                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        {{--{{$actors->links()}}--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/actors/show.blade.php
@extends('layouts.app')
@section('title', $actor->name.' '.$actor->surname)

@section('content')
        <div class="container">
                <div class="row justify-content-center">
                        <div class="col-md-8">
                                <div class="card">
                                        <div class="card-header">
                                                Pagina di {{$actor->name}} {{$actor->surname}}
                                                <a href="{{route('actors.edit', $actor->id)}}" class="float-right">
                                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                                </a>

                                        </div>

                                        <div class="card-body">
                                                <div class="row">
                                                        <div class="col-6">
                                                                <img src="{{$actor->path}}" style="max-width: 100%">
                                                        </div>
                                                        <div class="col-6">
                                                                <div class="row">
                                                                        <div class="col-12">
                                                                                Nome: {{$actor->name}}
                                                                        </div>
                                                                        <div class="col-12">
                                                                                Cognome: {{$actor->surname}}
                                                                        </div>
                                                                        <div class="col-12">
                                                                                Anno di nascita: {{$actor->year}}
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </div>
                                                <div>
                                                        <h2>Lista film di {{$actor->name}} {{$actor->surname}}</h2>
                                                       @forelse($actor->movies as $movie)
                                                                <div class="row">
                                                                        <div class="col-8">{{$movie->title}}</div>
                                                                        <div class="col-2">
                                                                                <a href="{{route('movies.show', $movie->id)}}">
                                                                                        <i class="fa fa-eye"></i>
                                                                                </a>
                                                                        </div>
                                                                        <div class="col-2">
                                                                                <button  type="submit" data-id="{{$movie->id}}" class="movie-delete btn btn-primary-outline">
                                                                                        <i class="fa fa-trash"></i>
                                                                                </button>
                                                                        </div>
                                                                </div>
                                                        @empty
                                                                Non vi sono film registrati
                                                        @endforelse
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
@endsection

@section('javascript')

    <script>
        $(document).ready(function () {

            $('.movie-delete').click(function (e) {
               var id = $(this).data('id');
               var row = $(this).closest('.row');
               $.ajax({
                    url: '/movies/'+id,
                    type: 'DELETE',
                    success: function () {
                        console.log('ci siamo');
                        console.log(this);
                        row.remove();
                    },
                   error: function (err) {
                       console.log('errore');
                   }
            })

                console.log('non ci siamo')
            })
        })
    </script>
@endsection