routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/ciao/{name?}/{surname?}/{year?}', 'HelloController@index')->name('hello')
    ->where('name', '[a-z,A-Z]+')
    ->where('surname', '[a-z]+')
    ->where('year', '[0-9]+');

//Route::resource('table', 'TableController')->only('index');

Route::get('table/{n?}', 'TableController@index')->where('n', '[0-9]+');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function (){
    Route::resource('actors', 'ActorController');
    Route::resource('movies', 'MovieController')->only('show', 'edit', 'update', 'destroy');
    Route::resource('permissions', 'PermissionController');
    Route::resource('users', 'UserController');
    Route::resource('todos', 'TodoController');
    Route::resource('users.permission', 'PermissionUserController');
    Route::get('/homejs', function (){
        return view('homejs');
    });
});





//Route::get('actors', 'ActorController@index');
//Route::post('actors', 'ActorController@store');
//Route::get('actors/{id}', 'ActorController@show');
//Route::put('actors/{id}', 'ActorController@update');
//Route::delete('actors/{id}', 'ActorController@destroy');
//
//Route::get('actors/create', 'ActorController@create');
//Route::get('actors/{id}/edit', 'ActorController@edit');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function permissions(){
        return $this->belongsToMany('App\Permission', 'permission_user', 'user_id', 'permission_id');
    }

    public function todos(){
        return $this->hasMany('App\Todo');
    }

    public function permissionIsset($perm){
        return $this->permissions()->where('name', '=', $perm);
    }

    public function getPermissionIsset($perm){
        return count($this->permissionIsset($perm)->get()) ? true : false;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use App\User;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index', ['users' => User::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }


    public function show(User $user)
    {
        if(Gate::denies('permission', 'editUser')){
            abort(403, "Non hai i permessi per modificare l'utente");
        }

        $permissions = Permission::notPermission($user->id)->select('permissions.id', 'permissions.name')->get();
        $permissionAll = Permission::listPermission($user->id)->select(array('permissions.id', 'permissions.name', 'permission_user.user_id'))->get();
//        foreach (Permission::all() as $perm){
//            $control = true;
//            foreach ($user->permissions as $p){
//                if($perm->id == $p->id){
//                    $control = false;
//                }
//            }
//            if($control){
//                array_push($permissions, $perm);
//            }
//        }

        return view('users.show', compact('user', 'permissions', 'permissionAll'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }


    public function update(Request $request, User $user)
    {

        //$user->permissions()->attach($request->input('permission'));
        $user->permissions()->sync($request->input('permissions'));
        return redirect()->route('users.show', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title', 'Lista utenti')

@section('content')
    <div class="container">
        <div class="row actor justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Lista utenti</div>

                    <div class="card-body">
                        @foreach($users as $user)
                            <div class="row my-3 badge-primary">
                                <div class="col-3">

                                </div>
                                <div class="col-9">
                                    <div class="row">
                                        <div class="col-8">
                                            <h4>{{$user->name}}</h4>
                                        </div>
                                        <div class="col-2">
                                            @can('permission', 'editUser')
                                            <a href="{{route('users.show', $user->id)}}">
                                                <i class="fa fa-address-card"></i>
                                            </a>
                                            @endcan
                                        </div>
                                        <div class="col-2">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', 'Pagina di '.$user->name)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Pagina di {{$user->name}}</div>

                    <div class="card-body">
                       <div class="row p-2">
                           <div class="col-6 p-2">
                               Nome: {{$user->name}}
                           </div>
                           <div class="col-6 p-2">
                               Email: {{$user->email}}
                           </div>
                       </div>
                        {{--<div>--}}
                            {{--<h2>Permessi dell'utente</h2>--}}
                            {{--@forelse($user->permissions as $permission)--}}
                                {{--<div class="row p-2 m1">--}}
                                    {{--<div class="col-10">--}}
                                        {{--{{$permission->name}}--}}
                                    {{--</div>--}}
                                    {{--<div class="col-2">--}}
                                        {{--<form action="{{route('users.permission.destroy', [$user->id, $permission->id])}}" method="POST">--}}
                                            {{--@csrf--}}
                                            {{--@method('DELETE')--}}
                                            {{--<button class="btn btn-primary-outline">--}}
                                                {{--<i class="fa fa-trash" aria-hidden="true"></i>--}}
                                            {{--</button>--}}
                                        {{--</form>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--@empty--}}
                                {{--L'utente non ha permessi--}}
                            {{--@endforelse--}}
                        {{--</div>--}}
                        <div class="row m-4">
                            <div class="col-12">
                                <h2>Tutti i permessi</h2>
                                <form action="{{route('users.update', $user->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    @foreach($permissionAll as $p)
                                        <div class="form-group">
                                            <input type="checkbox" name="permissions[]" value="{{$p->id}}" {{$p->user_id ? 'checked' : ''}}>
                                            <label>{{$p->name}}</label>
                                        </div>
                                    @endforeach
                                    <button class="btn btn-primary float-right">Setta permessi</button>
                                </form>

                            </div>
                        </div>
                        {{--<div class="row">--}}
                            {{--<div class="col-12">--}}
                                {{--@if(count($permissions))--}}
                                    {{--<form action="{{route('users.update', $user->id)}}" method="POST">--}}
                                        {{--@csrf--}}
                                        {{--@method('PUT')--}}
                                        {{--<select name="permission">--}}
                                            {{--@foreach($permissions as $p)--}}
                                                {{--<option value="{{$p->id}}">{{$p->name}}</option>--}}
                                            {{--@endforeach--}}
                                        {{--</select>--}}
                                        {{--<button class="btn btn-primary float-right">Aggiungi Permesso</button>--}}
                                    {{--</form>--}}

                                {{--@endif--}}
                            {{--</div>--}}
                        {{--</div>--}}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection